### ISSUE TITLE
How to do an update without duplication 

### ISSUE THREAD

**Issue by zain-creation** [sergeyksv/tingodb#101]
Hi,
i want to do an update of document without duplication of line in the collection file ???

thnks :)

**Comment by sergeyksv** [comment]
In order to ensure data integrity collection file is used in append mode. There is no in-place editing are allowed. So once you modify record you will see new record written into collection file. However logically it will be recognized as one record. 
There is db.compact and collection.compact function that can be used to remove old data. Compaction also triggered automatically when space overuse ratio reach some limit,

**Comment by zain-creation** [comment]
thnks sergey :)

**Comment by colinbes** [comment]
Regarding "Compaction also triggered automatically...", is this only on initialization or any time database is accessed? I assume it's only on initialization?

**Comment by sergeyksv** [comment]
Yes, automatic on initialization only.
